; tools/contract/base-paths.x — every base-object field as a first/rest path.
;
; SINGLE SOURCE OF TRUTH for reflective navigation of the interpreter state
; (the third layout contract, after tools/contract/base-layout.x -- the x-eval spine
; layout -- and tools/contract/obj-layout.x -- the per-object header).  The base
; object's C accessors are pure first/rest macro chains across three
; headers (include/x-eval-layout.h, ext/x-expr/include/x-base.h, and the
; error-handler object in include/x-eval.h); this file is those chains
; flattened into walkable step lists.  Consumed:
;   1. by X at runtime: lib/x/boot/reflect.x walks these paths from (%base)
;      to reach any interpreter cell (the pure-X accessors read them)
;   2. tools/check/base-paths.sh (make check-base-paths) -- re-derives every
;      path from the headers and diffs, so a spine change that moves a cell
;      fails the build before anything runs
;
; FORMAT (rigid, one entry per line -- the awk parses the same bytes):
;   (name root step...)
; root is `base` (walk from the (%base) object), `handler` (walk from an
; error-handler object), or `type` (walk from a type-tree object).  Steps are
; f (first) / r (rest), applied left to right.  A field labelled `cell` has
; its value in the cell's first slot; see the C headers for each field's label.
; Regenerate with: sh tools/check/base-paths.sh --gen

(def %base-paths (lit (
  (env base r f f)
  (env base r f f f)
  (env-root base r f f r)
  (ctrl base r f r)
  (save-stack base r f r f f)
  (error-handler base r f r f r)
  (tco-expr base r f r r f)
  (tco-env base r f r r r)
  (type-alist base r r f f f)
  (io-state base r r f r)
  (line base r r f r f)
  (true base r r f r r f)
  (false base r r f r r r)
  (profile-evals base r r r f f r f)
  (profile-tco base r r r f f r r f)
  (profile-assoc-calls base r r r f f r r r f)
  (profile-assoc-steps base r r r f f r r r r f)
  (profile-sym-find-calls base r r r f f r r r r r f)
  (profile-sym-find-steps base r r r f f r r r r r r f)
  (profile-gc-runs base r r r f f r r r r r r r f)
  (profile-bst-hits base r r r f f r r r r r r r r f)
  (profile-bst-misses base r r r f f r r r r r r r r r f)
  (profile-env-steps base r r r f f r r r r r r r r r r f)
  (state base r r r r r r)
  (eval-list base r r r r r r f)
  (token-cache base r r r r r r r f)
  (sigint base r r r r r r r r f)
  (err base r r r r r r r r r f)
  (prims base r r r r r r r r r r f)
  (file base r r r r r r r r r r r f)
  (err-line base r r r r r r r r r r r r f)
  (err-file base r r r r r r r r r r r r r f)
  (file-registry base r r r r r r r r r r r r r r)
  (base base r)
  (io-fields base r r f)
  (files base r r f f r)
  (filein base r r f f r f)
  (fileout base r r f f r r f)
  (fileerr base r r f f r r r f)
  (write-buf base r r f f r r r r f)
  (buffer base r r f f r r r r r f)
  (meta-fields base r r r)
  (profile base r r r f f)
  (profile-allocs base r r r f f f)
  (hooks base r r r f r)
  (hook-type-name base r r r f r f)
  (hook-units base r r r f r r f)
  (hook-length base r r r f r r r f)
  (hook-error base r r r f r r r r f)
  (heap-fields base r r r r f)
  (obj-meta-extra base r r r r f f)
  (heap-mark base r r r r f r f)
  (heap-free base r r r r f r r f)
  (heap-mark-hooks base r r r r f r r r f)
  (heap-free-hooks base r r r r f r r r r f)
  (heap-mark-roots base r r r r f r r r r r f)
  (heap-root-chain base r r r r f r r r r r r f)
  (alloc-fields base r r r r r f)
  (alloc-count base r r r r r f f)
  (alloc-limit base r r r r r f r f)
  (alloc-error base r r r r r f r r f)
  (error-handler-saved-env handler r f f)
  (error-handler-error handler r r f)
  (error-handler-line handler r r r)
  (arg-exp base f)
  (type-name-stack type f)
  (type-name type f f)
  (type-data-stack type r f)
  (type-data type r f f)
  (type-heap type r r f)
  (type-mark-stack type r r f f)
  (type-mark type r r f f f)
  (type-make-stack type r r f r f)
  (type-make type r r f r f f)
  (type-free-stack type r r f r r f)
  (type-free type r r f r r f f)
  (type-clone-stack type r r f r r r f)
  (type-clone type r r f r r r f f)
  (type-units-stack type r r f r r r r f)
  (type-units type r r f r r r r f f)
  (type-length-stack type r r f r r r r r f)
  (type-length type r r f r r r r r f f)
  (type-proc type r r r f)
  (type-call-stack type r r r f f)
  (type-call type r r r f f f)
  (type-eval-stack type r r r f r f)
  (type-eval type r r r f r f f)
  (type-cvt type r r r r f)
  (type-from-stack type r r r r f f)
  (type-from type r r r r f f f)
  (type-to-stack type r r r r f r f)
  (type-to type r r r r f r f f)
  (type-io type r r r r r f)
  (type-analyse-stack type r r r r r f f)
  (type-analyse type r r r r r f f f)
  (type-delimit-stack type r r r r r f r f)
  (type-delimit type r r r r r f r f f)
  (type-read-stack type r r r r r f r r f)
  (type-read type r r r r r f r r f f)
  (type-write-stack type r r r r r f r r r f)
  (type-write type r r r r r f r r r f f)
  (type-display-stack type r r r r r f r r r r f)
  (type-display type r r r r r f r r r r f f)
  (type-iter-fields type r r r r r r f)
  (type-iter-stack type r r r r r r f f)
  (type-iter type r r r r r r f f f)
  (type-ops-fields type r r r r r r r f)
  (type-ops-stack type r r r r r r r f f)
  (type-ops type r r r r r r r f f f)
  (type-image-fields type r r r r r r r r f)
  (type-save-stack type r r r r r r r r f f)
  (type-save type r r r r r r r r f f f)
  (type-load-stack type r r r r r r r r f r f)
  (type-load type r r r r r r r r f r f f)
  (type-arg-type base f)
)))
