#!/bin/sh
# gen-build-params.sh -- the facts of THIS BUILD, as declarations.
#
#   Usage: sh tools/contract/gen-build-params.sh <triple> [cc]   (writes stdout)
#
# x-engine.xon deliberately carries no (param ...) rows: it is generated from
# SOURCE, and word size, byte order and architecture are facts of a BUILD.  The
# same source tree yields a 32-bit and a 64-bit engine whose capability sets and
# layout digests are byte-identical.  This file is the other half -- generated at
# build time, installed beside the binary, and read by x-lang instead of inferred.
#
# WHY THE COMPILER AND NOT uname.  A cross-compiled engine must report its TARGET,
# not the machine that built it.  __SIZEOF_POINTER__ and __BYTE_ORDER__ come from
# the compiler that is actually producing this binary, so they follow the target
# across a cross-build where `uname -m` would confidently answer for the host.
# The triple is the compiler's own -dumpmachine for the same reason.
#
# UNKNOWN IS A VALUE, NOT A GUESS.  If a fact cannot be established the row says
# `unknown` rather than defaulting: a wrong `(param arch x86-64)` is worse than an
# absent one, because x-lang would believe it.  A consumer that finds `unknown`
# falls back to the interim it already has.
set -e

TRIPLE="${1:-}"
CC_="${2:-cc}"
[ -n "$TRIPLE" ] || { echo "gen-build-params: usage: gen-build-params.sh <triple> [cc]" >&2; exit 2; }

# Strip any quoting the make variable carried.
TRIPLE=$(printf '%s' "$TRIPLE" | tr -d '"' | tr 'A-Z' 'a-z')

# --- word size and byte order, from the compiler producing this binary --------
wordsize=$(printf '__SIZEOF_POINTER__\n' | $CC_ -E -P - 2>/dev/null | tr -d ' \t\n' || true)
case "$wordsize" in
	4|8) ;;
	*) wordsize=unknown ;;
esac

endian=$(printf '#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__\nlittle\n#else\nbig\n#endif\n' \
	| $CC_ -E -P - 2>/dev/null | tr -d ' \t\n' || true)
case "$endian" in
	little|big) ;;
	*) endian=unknown ;;
esac

# --- os and arch, from the triple ---------------------------------------------
# Parsed HERE, once, at build time, by the project that owns the triple -- which
# is the whole point: x-lang consuming a declaration instead of every module
# sniffing the same string at runtime.
case "$TRIPLE" in
	*darwin*) os=darwin ;;
	*linux*)  os=linux ;;
	*bsd*)    os=bsd ;;
	*)        os=unknown ;;
esac

# Darwin spells A64 "arm64"; GNU triplets spell it "aarch64".  One place knows.
case "$TRIPLE" in
	arm64*|aarch64*)   arch=arm64 ;;
	x86_64*|amd64*)    arch=x86-64 ;;
	i[3456]86*)        arch=i386 ;;
	*)                 arch=unknown ;;
esac

printf '; x-engine-build.xon -- generated by tools/contract/gen-build-params.sh at\n'
printf '; build time; do not edit.  These are facts of THIS BINARY, not of the\n'
printf '; source tree: a 32-bit and a 64-bit build of the same engine differ here\n'
printf '; and nowhere else in the contract.  Read, never evaluated.\n'
printf '(param machine "%s")\n' "$TRIPLE"
printf '(param word-size %s)\n' "$wordsize"
printf '(param endian %s)\n' "$endian"
printf '(param os %s)\n' "$os"
printf '(param arch %s)\n' "$arch"
